### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [jordanhunt22/Parstagram#1]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:
- The current signed in user is persisted across app restarts

Can you update this and resubmit?

**Comment by jordanhunt22** [comment]
I updated my README with a GIF showing this required user story and resubmitted to CodePath.

**Comment by codepathreview** [comment]
Nice work, Jordan. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
